### ISSUE TITLE
Deployment approach

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [ec-jrc/Thalassa#14]
Similar to #13, for deployment there are multiple options to consider, and each of them has its own way of building:
- Virtual env: uses poetry to build and then installs the wheel into the virtual env
- Docker: uses poetry to build and then installs the wheel into the image
- Conda: uses panel to start the Jupyter notebook

In my experience using the notebook to deploy remotely could become tricky as each connection to the port where panel is served is going to create a new server on a new dynamically chosen port. Instead it seems to be a better idea to serve the applications using the panel Python API. This way one could open a single port on the remote machine on which the single Bokeh server listens and can (?) server multiple users.

**Comment by pmav99** [comment]
yes, this is messy, too. I am sorry for that. what I mentioned in #13 applies here, too...

Anyhow, deploying a web app is quite vendor specific. Each deployment environment can have its own policies. E.g. you might not be able to use conda, or you might have to use your company's private PYPI mirror, or you might have a policy that forces you to build all the packages from source etc, etc. 

This is why I think we should not try to overachieve here. I think that as the first step we should provide the minimum. Which is:

- give guidance WRT the required binaries dependencies. For example we need python 3.9, GDAL 3.2.1, Proj 8+ and eccodes 2.21+ (this is random stuff, we don't need all of that).
- a `requirements.txt` with pinned versions of all the python dependencies.

With this info anyone should be able to deploy in their own environment. Now if they want to use conda or docker or compile from scratch, that's their choice.

If we want to take this a step further, then providing a basic Dockerfile as a guidance would not be a bad idea, but I think we should avoid deployment specific instructions on thalassa (e.g. `docker/run.sh` etc). The point is that what works or is needed on e.g. TACC is not necessarily needed or transferable on different environments. The fact that you already had to change the existing scripts yourselves is a good example of this. Not to mention that having such scripts publicly can give hints to potential attackers.

Going beyond that, e.g. creating/providing an actual docker image means that we need to bother with docker registries, organizations on docker hub etc, and anyhow, it is something that can be tackled at a later time.

**Comment by SorooshMani-NOAA** [comment]
I agree that we should not overachieve and that it's hard to have support for everything. The point of creating these issue tickets were to discuss the development path forward. In specific we made some changes to deploy on TACC, non of which might need to go into Thalassa base code. I just want us to come up with a clean instruction of using Thalassa and maybe a few examples of how to deploy it in various cases. As you said if we go with a very specific deployment approach it might make it unusable for different organizations, etc.

Deploying on a remote machine would be a good example to have. It doesn't need to be a fancy example, but just how to set it up to work. e.g. to serve on a single port on a remote machine where you can forward ports. I think this is basic enough to support along with local deployment. Using docker or not we should make sure to have dependencies laid out such that it's easy to get it to work.

I am a big fan of keeping everything as simple as possible and having the least number of dependencies. If we can list all the library dependencies for the end user to take care of and then have a setup.py or .cfg that takes care of python side packages, then we're golden. Then the user can use any method (conda/apt/Docker/etc.) to install necessary libraries and pip will take care of Python packages.

**Comment by pmav99** [comment]
I think that this has been resolved in v0.2. Closing for now. Feel free to reopen if I am missing something
