### ISSUE TITLE
Show grid (mesh) plus water depth as default background

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [ec-jrc/Thalassa#21]
- Would you please rename grid to mesh? At NOAA, we use mesh for unstructured and grid for structured domains.
- It would be great to explore rendering water depth as the background values for the mesh wireframe.

**Comment by pmav99** [comment]
> It would be great to explore rendering water depth as the background values for the mesh wireframe.

Is there some tiling service that provides water depth data?
https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by pmav99** [comment]
I believe this is currently supported in the current master. You just need to have the depth as a netcdf variable. Closing
