### ISSUE TITLE
ruyaml conda dependency 

### ISSUE THREAD

**Issue by brey** [ec-jrc/Thalassa#22]
I have worked out an `environment.yaml` for the conda recipe version. There is an issue with the `ruyaml` dependency as a result of the fork from `ruamel.yaml`. 

The conda version is available from the latter but not from the former (yet). 

I am not sure if we can revert to `ruamel.yaml` or using the fork is important but we can elevate the issue upstream if needed.

**Comment by pmav99** [comment]
No problem in using `ryamel.yaml`. This is not a "hard" dependency. We only use it to parse the logging configuration. We could convert it to json and get rid of it completely.
