### ISSUE TITLE
setup github-actions for linters

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/Thalassa#29]

**Comment by pmav99** [comment]
@brey I tried to add pre-commit.ci to `ec-jrc/Thalassa` but I don't have the permissions for that:
![image](https://user-images.githubusercontent.com/411196/225230878-06356093-2a95-4009-958b-c6cf4a7e0717.png)

Can you do it?

**Comment by brey** [comment]
Try again. I made you admin.

**Comment by pmav99** [comment]
Thanks. It should work now.
