### ISSUE TITLE
Add temperature and salinity variables to view and get time series

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [ec-jrc/Thalassa#31]

**Comment by saeed-moghimi-noaa** [comment]
Hi @wzhengui , What do you think about this? @saeed-moghimi-noaa

**Comment by wzhengui** [comment]
Hi Saeed:

1). I just finished the time series, and updated the code in "add_timeseries" branch.  If you have time, can you help review it also? 

2). For working on salinity and temperature view, I have no problem. Maybe, we can discuss this more tomorrow. 

Thanks,
Zhengui

**Comment by pmav99** [comment]
Implemented on current master
