### ISSUE TITLE
Error when reproducing timeseries branch

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [ec-jrc/Thalassa#34]
All,

Is this error familiar to you?

(Thalassa) moghimi:Thalassa/ (timeseries) $ panel serve run.py       [22:59:52]
2022-01-27 22:59:53,604 Starting Bokeh server version 2.4.2 (running on Tornado 6.1)
2022-01-27 22:59:53,605 User authentication hooks NOT provided (default user enabled)
2022-01-27 22:59:53,607 Bokeh app running at: http://localhost:5006/run
2022-01-27 22:59:53,607 Starting Bokeh server with process id: 87984
2022-01-27 22:59:59,048; ERROR   ; [87984 - 140292251289408]; thalassa.ui                        ; error               ;  32: ## Please select a `dataset_file` and click on the `Render` button.

-Saeed

**Comment by pmav99** [comment]
Yes, this was not a real error. I reduced the severity of the log message to info

**Comment by saeed-moghimi-noaa** [comment]
I still can not get Thalassa up and running.

On Friday, January 28, 2022, pmav99 ***@***.***> wrote:
> Yes, this was not a real error. I reduced the severity of the log message
to info
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/NhOZ3nHyFjLv0_tRKchBtSCOAMTItkHYcHc0_CHUWEc2ScwN8uD-lNYTOmO-1VUyKS8AgNPiDyyE_zTugJjOa0zY88sYAeXCsZojSN0X2I8UYI338i0rueyvtyqX0MphWxAiq4fgMGJ3azBgOWttPVNa_FZF9aiC141NvnUFY_1mQTfA2l2jQ_L094V0V5jdZK7VtdKoVkMnEo8gyWPBsNdSzxYS4p-ywaB27Md2vQ=s0-d-e1-ft#https://github.com/notifications/beacon/APZULD5YVBGP6HSJNHRM2F3UYJDFRA5CNFSM5M7W2SY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHUEH6VA.gif>Message
ID: ***@***.***>

-- 
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by pmav99** [comment]
Is this related to what you showed us after the Friday meeting a couple of weeks ago? If yes, I would suggest to look if the error is related to WSL's network configuration and/or windows Firewall.

**Comment by saeed-moghimi-noaa** [comment]
I tried the system on my linux machine. I saw the same thing. -Saeed
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by saeed-moghimi-noaa** [comment]
[Solved]: There is a *bug *in the code. The code is expected to have a
dataset.nc in the data folder. if not, it gives you a blank screen without
any error or warning.
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by saeed-moghimi-noaa** [comment]
[Solved]: There is a bug in the code. The code is expected to have a dataset.nc in the data folder. if not, it gives you a blank screen without any error or warning.
