### ISSUE TITLE
Add support for ADCIRC

### ISSUE THREAD

**Issue by pmav99** [ec-jrc/Thalassa#57]
It would be great if thalassa could support ADCIRC output, too.

@saeed-moghimi-noaa could you provide a sample Netcdf file?

**Comment by saeed-moghimi-noaa** [comment]
Hi @pmav99 

See attached `fort.63.nc` which contains water surface elevation time series.

Thanks,
-Saeed

[fort.63.zip](https://github.com/ec-jrc/Thalassa/files/10867068/fort.63.zip)

**Comment by pmav99** [comment]
@saeed-moghimi-noaa current master should support ADCIRC

Q1: Does ADCIRC support quad elements? If yes do we have an example?
Q2: Does ADCIRC support 3D meshes? If yes do we have an example?

**Comment by saeed-moghimi-noaa** [comment]
Thanks @pmav99  for working on this. The answer to both question is NO.

**Comment by pmav99** [comment]
It seems that ADCIRC output files may use a somewhat different schema depending on the configuration of the model. 

After 9f8821e04714f862df53f53d0857244f1273de34 we are able to support both the schema that is uploaded in the 2nd post and the STOFS 2D Global schema.

I am closing the issue. If other ADCIRC files/schemas need to be supported, then new tickets should be opened.
