### ISSUE TITLE
default_kwargs not recognised with custom engine

### ISSUE THREAD

**Issue by tomsail** [ec-jrc/Thalassa#86]
When trying to open a telemac file through thalassa, 

```python 
ds = thalassa.open_dataset("input.slf", engine="selafin")
```
with [xarray-selafin](https://github.com/seareport/xarray-selafin) custom engine 
I have this error: 
```
  File "/home/tomsail/work/gist/animations/.venv/lib/python3.11/site-packages/thalassa/api.py", line 82, in open_dataset
    ds = xr.open_dataset(path, **(default_kwargs | kwargs))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomsail/work/gist/animations/.venv/lib/python3.11/site-packages/xarray/backends/api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
TypeError: SelafinBackendEntrypoint.open_dataset() got an unexpected keyword argument 'mask_and_scale'
```

Should I add this argument (maybe even all `[default kwargs](https://github.com/ec-jrc/Thalassa/blob/b9d977cd6999e73f5ad884e9e7b96d4041b60827/thalassa/api.py#L76)` to my custom backend?) or should your hook be more forgiving across engines?

**Comment by pmav99** [comment]
I think was fixed by: https://github.com/ec-jrc/Thalassa/commit/d264508e098b295d21104a68a0ee43cc0dc6e32e#diff-7d188c917a7509674fb8898f4ce81a70063d10c443627229a44c3d7263d9198dR77
