### ISSUE TITLE
Error in Plotting STOFS-3D-Atlantic Data

### ISSUE THREAD

**Issue by AtiehAlipour-NOAA** [ec-jrc/Thalassa#88]
Hi, I am trying to use the Thalassa package to read and plot STOFS-3D-Atlantic outputs. While thalassa.open_dataset and thalassa.plot work fine with *schout_adcirc outputs, it does not plot other outputs required to visualize current output, such as stofs_3d_atl.t12z.f001_024.field2d.nc. Please see the plot below for an example. Any suggestions on how I can use thalassa.open_dataset and thalassa.plot to plot the data correctly? Thanks for your help and time.

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/aa3e5180-1ded-4804-8166-46010dd3760d)

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/ea6cf022-6fa9-4f32-9d28-26006a37d88d)

**Comment by pmav99** [comment]
Hello Atieh

I am afraid we haven't really looked into 3D output.

Judging from the screenshots, my guess is that there is some issue with the element connectivity.

```
ds = xr.open_dataset("~/Downloads/stofs_3d_atl.t12z.n001_024.field2d.nc")
ds.dims
ds.SCHISM_hgrid_face_nodes.min().values
ds.SCHISM_hgrid_face_nodes.max().values
```
outputs
```
FrozenMappingWarningOnValuesAccess({'time': 24, 'nSCHISM_hgrid_node': 2654153, 'nSCHISM_hgrid_face': 5039151, 'nMaxSCHISM_hgrid_face_nodes': 3})
array(3, dtype=int32)
array(2653944, dtype=int32)
```
Do notice that the node connectivity only starts from 3 and only reaches up to 2653944 instead of 2654153. 

So, it seems that these files don't contain the full mesh for whatever reason. 

-----

related: https://github.com/ec-jrc/Thalassa/issues/61

**Comment by pmav99** [comment]
You can try to copy the mesh connectivity from the `schout_adcirc_*` file and then it ~should~ might work. You will probably need to rename a bunch of dimensions though.

**Comment by AtiehAlipour-NOAA** [comment]
@pmav99 Thank you so much for the great suggestion. I tried to use the format and names inside the shout_adcirc file and rename and replace values and dimensions in field2d.nc files.  

First I read the nc files.
![image](https://github.com/ec-jrc/Thalassa/assets/148251584/5e30ed61-8f2a-45dc-967b-d00c888e7ca0)

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/f2f0b05f-694f-4009-98de-6b5902a0b42d)


Then I renamed and replaced the dimensions and variables in field2d.nc files. 

```
ds2= ds2.rename({'nSCHISM_hgrid_node': 'node', 'nSCHISM_hgrid_face': 'nele', 'nMaxSCHISM_hgrid_face_nodes': 'nvertex'})
ds2 = ds2.drop_dims('nele')
ds2['nele'] = ds['nele']
ds2['nvertex']=ds['nvertex']
ds2['element']= ds['element']
ds2= ds2.rename({'SCHISM_hgrid_node_x': 'x', 'SCHISM_hgrid_node_y': 'y'})
ds2
```

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/851b1a4f-bd01-4df7-a7c8-ffba9b7bc7ce)

I normalized and cropped the data using Thalassa.

When I plot the data the depth values look OK, but for the rest of variables, there are a lot of missing data. 

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/d9ddbef1-e778-4452-a146-8f7d041bab37)

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/84c160ba-6b7c-4e36-9b7e-0cdcf5191d85)

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/9494dd95-f88d-447a-b205-b1c269fb5333)

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/2e1176df-66fb-4fe9-9e55-eea3b65ca75d)


The same happens when I copy each variable to shout_adcirc file.

**Comment by pmav99** [comment]
Hmm... The missing values seem to be on triangles that are over land. So it could be that some kind of mask is applied on the dataset. Have you checked if there are values there? I suspect that there are `nan`s for `elev` etc. 

Check the original netcdf files. Not the normalized datasets. E.g. with
``` python
ds_orig = xr.open_dataset(...)
ds_orig.isel(nSCHISM_hgrid_node=0).elev.values
```

If this is the case, this should also explain why these files contain a subset of the connectivity. The mask must have been applied there, too.

**Comment by AtiehAlipour-NOAA** [comment]
@pmav99, you're correct. I looked into the nodes in the original dataset near the areas that show as `nan` in the plots, and it seems that most of them are `nan`. Thanks a lot for your help and time.

![image](https://github.com/ec-jrc/Thalassa/assets/148251584/167f9bc3-b864-403c-9c0b-bc9a03008263)

**Comment by pmav99** [comment]
OK. I guess I will just close the issue.
